name: Periodic health check

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  healtcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.4
        with:
          url: https://arkuar-cicdpokedex.herokuapp.com/health
          max-attempts: 3
          retry-delay: 5s